/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */


#ifndef SWIG_TEMPLATE_DISAMBIGUATOR
#  if defined(__SUNPRO_CC) 
#    define SWIG_TEMPLATE_DISAMBIGUATOR template
#  else
#    define SWIG_TEMPLATE_DISAMBIGUATOR 
#  endif
#endif

/***********************************************************************
 * swigrun.swg
 *
 *     This file contains generic CAPI SWIG runtime support for pointer
 *     type checking.
 *
 ************************************************************************/

/* This should only be incremented when either the layout of swig_type_info changes,
   or for whatever reason, the runtime changes incompatibly */
#define SWIG_RUNTIME_VERSION "1"

/* define SWIG_TYPE_TABLE_NAME as "SWIG_TYPE_TABLE" */
#ifdef SWIG_TYPE_TABLE
#define SWIG_QUOTE_STRING(x) #x
#define SWIG_EXPAND_AND_QUOTE_STRING(x) SWIG_QUOTE_STRING(x)
#define SWIG_TYPE_TABLE_NAME SWIG_EXPAND_AND_QUOTE_STRING(SWIG_TYPE_TABLE)
#else
#define SWIG_TYPE_TABLE_NAME
#endif

#include <string.h>

#ifndef SWIGINLINE
#if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#  define SWIGINLINE inline
#else
#  define SWIGINLINE
#endif
#endif

/*
  You can use the SWIGRUNTIME and SWIGRUNTIMEINLINE macros for
  creating a static or dynamic library from the swig runtime code.
  In 99.9% of the cases, swig just needs to declare them as 'static'.
  
  But only do this if is strictly necessary, ie, if you have problems
  with your compiler or so.
*/
#ifndef SWIGRUNTIME
#define SWIGRUNTIME static
#endif
#ifndef SWIGRUNTIMEINLINE
#define SWIGRUNTIMEINLINE SWIGRUNTIME SWIGINLINE
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef void *(*swig_converter_func)(void *);
typedef struct swig_type_info *(*swig_dycast_func)(void **);

typedef struct swig_type_info {
  const char             *name;
  swig_converter_func     converter;
  const char             *str;
  void                   *clientdata;
  swig_dycast_func        dcast;
  struct swig_type_info  *next;
  struct swig_type_info  *prev;
} swig_type_info;

/* 
  Compare two type names skipping the space characters, therefore
  "char*" == "char *" and "Class<int>" == "Class<int >", etc.

  Return 0 when the two name types are equivalent, as in
  strncmp, but skipping ' '.
*/
SWIGRUNTIME int
SWIG_TypeNameComp(const char *f1, const char *l1,
		  const char *f2, const char *l2) {
  for (;(f1 != l1) && (f2 != l2); ++f1, ++f2) {
    while ((*f1 == ' ') && (f1 != l1)) ++f1;
    while ((*f2 == ' ') && (f2 != l2)) ++f2;
    if (*f1 != *f2) return *f1 - *f2;
  }
  return (l1 - f1) - (l2 - f2);
}

/*
  Check type equivalence in a name list like <name1>|<name2>|...
*/
SWIGRUNTIME int
SWIG_TypeEquiv(const char *nb, const char *tb) {
  int equiv = 0;
  const char* te = tb + strlen(tb);
  const char* ne = nb;
  while (!equiv && *ne) {
    for (nb = ne; *ne; ++ne) {
      if (*ne == '|') break;
    }
    equiv = SWIG_TypeNameComp(nb, ne, tb, te) == 0;
    if (*ne) ++ne;
  }
  return equiv;
}

/*
  Register a type mapping with the type-checking
*/
SWIGRUNTIME swig_type_info *
SWIG_TypeRegisterTL(swig_type_info **tl, swig_type_info *ti) {
  swig_type_info *tc, *head, *ret, *next;
  /* Check to see if this type has already been registered */
  tc = *tl;
  while (tc) {
    /* check simple type equivalence */
    int typeequiv = (strcmp(tc->name, ti->name) == 0);   
    /* check full type equivalence, resolving typedefs */
    if (!typeequiv) {
      /* only if tc is not a typedef (no '|' on it) */
      if (tc->str && ti->str && !strstr(tc->str,"|")) {
	typeequiv = SWIG_TypeEquiv(ti->str,tc->str);
      }
    }
    if (typeequiv) {
      /* Already exists in the table.  Just add additional types to the list */
      if (ti->clientdata) tc->clientdata = ti->clientdata;
      head = tc;
      next = tc->next;
      goto l1;
    }
    tc = tc->prev;
  }
  head = ti;
  next = 0;

  /* Place in list */
  ti->prev = *tl;
  *tl = ti;

  /* Build linked lists */
  l1:
  ret = head;
  tc = ti + 1;
  /* Patch up the rest of the links */
  while (tc->name) {
    head->next = tc;
    tc->prev = head;
    head = tc;
    tc++;
  }
  if (next) next->prev = head;
  head->next = next;

  return ret;
}

/*
  Check the typename
*/
SWIGRUNTIME swig_type_info *
SWIG_TypeCheck(const char *c, swig_type_info *ty) {
  swig_type_info *s;
  if (!ty) return 0;        /* Void pointer */
  s = ty->next;             /* First element always just a name */
  do {
    if (strcmp(s->name,c) == 0) {
      if (s == ty->next) return s;
      /* Move s to the top of the linked list */
      s->prev->next = s->next;
      if (s->next) {
        s->next->prev = s->prev;
      }
      /* Insert s as second element in the list */
      s->next = ty->next;
      if (ty->next) ty->next->prev = s;
      ty->next = s;
      s->prev = ty;
      return s;
    }
    s = s->next;
  } while (s && (s != ty->next));
  return 0;
}

/*
  Cast a pointer up an inheritance hierarchy
*/
SWIGRUNTIMEINLINE void *
SWIG_TypeCast(swig_type_info *ty, void *ptr) {
  return ((!ty) || (!ty->converter)) ? ptr : (*ty->converter)(ptr);
}

/* 
   Dynamic pointer casting. Down an inheritance hierarchy
*/
SWIGRUNTIME swig_type_info *
SWIG_TypeDynamicCast(swig_type_info *ty, void **ptr) {
  swig_type_info *lastty = ty;
  if (!ty || !ty->dcast) return ty;
  while (ty && (ty->dcast)) {
    ty = (*ty->dcast)(ptr);
    if (ty) lastty = ty;
  }
  return lastty;
}

/*
  Return the name associated with this type
*/
SWIGRUNTIMEINLINE const char *
SWIG_TypeName(const swig_type_info *ty) {
  return ty->name;
}

/*
  Return the pretty name associated with this type,
  that is an unmangled type name in a form presentable to the user.
*/
SWIGRUNTIME const char *
SWIG_TypePrettyName(const swig_type_info *type) {
  /* The "str" field contains the equivalent pretty names of the
     type, separated by vertical-bar characters.  We choose
     to print the last name, as it is often (?) the most
     specific. */
  if (type->str != NULL) {
    const char *last_name = type->str;
    const char *s;
    for (s = type->str; *s; s++)
      if (*s == '|') last_name = s+1;
    return last_name;
  }
  else
    return type->name;
}

/*
  Search for a swig_type_info structure
*/
SWIGRUNTIME swig_type_info *
SWIG_TypeQueryTL(swig_type_info *tl, const char *name) {
  swig_type_info *ty = tl;
  while (ty) {
    if (ty->str && (SWIG_TypeEquiv(ty->str,name))) return ty;
    if (ty->name && (strcmp(name,ty->name) == 0)) return ty;
    ty = ty->prev;
  }
  return 0;
}

/* 
   Set the clientdata field for a type
*/
SWIGRUNTIME void
SWIG_TypeClientDataTL(swig_type_info *tl, swig_type_info *ti, void *clientdata) {
  swig_type_info *tc, *equiv;
  if (ti->clientdata) return;
  /* if (ti->clientdata == clientdata) return; */
  ti->clientdata = clientdata;
  equiv = ti->next;
  while (equiv) {
    if (!equiv->converter) {
      tc = tl;
      while (tc) {
        if ((strcmp(tc->name, equiv->name) == 0))
          SWIG_TypeClientDataTL(tl,tc,clientdata);
        tc = tc->prev;
      }
    }
    equiv = equiv->next;
  }
}

/* 
   Pack binary data into a string
*/
SWIGRUNTIME char *
SWIG_PackData(char *c, void *ptr, size_t sz) {
  static char hex[17] = "0123456789abcdef";
  unsigned char *u = (unsigned char *) ptr;
  const unsigned char *eu =  u + sz;
  register unsigned char uu;
  for (; u != eu; ++u) {
    uu = *u;
    *(c++) = hex[(uu & 0xf0) >> 4];
    *(c++) = hex[uu & 0xf];
  }
  return c;
}

/* 
   Unpack binary data from a string
*/
SWIGRUNTIME const char *
SWIG_UnpackData(const char *c, void *ptr, size_t sz) {
  register unsigned char *u = (unsigned char *) ptr;
  register const unsigned char *eu =  u + sz;
  for (; u != eu; ++u) {
    register int d = *(c++);
    register unsigned char uu = 0;
    if ((d >= '0') && (d <= '9'))
      uu = ((d - '0') << 4);
    else if ((d >= 'a') && (d <= 'f'))
      uu = ((d - ('a'-10)) << 4);
    else 
      return (char *) 0;
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu |= (d - '0');
    else if ((d >= 'a') && (d <= 'f'))
      uu |= (d - ('a'-10));
    else 
      return (char *) 0;
    *u = uu;
  }
  return c;
}

/*
  This function will propagate the clientdata field of type to any new
  swig_type_info structures that have been added into the list of
  equivalent types.  It is like calling SWIG_TypeClientData(type,
  clientdata) a second time.
*/
SWIGRUNTIME void
SWIG_PropagateClientDataTL(swig_type_info *tl, swig_type_info *type) {
  swig_type_info *equiv = type->next;
  swig_type_info *tc;
  if (!type->clientdata) return;
  while (equiv) {
    if (!equiv->converter) {
      tc = tl;
      while (tc) {
        if ((strcmp(tc->name, equiv->name) == 0) && !tc->clientdata)
          SWIG_TypeClientDataTL(tl,tc, type->clientdata);
        tc = tc->prev;
      }
    }
    equiv = equiv->next;
  }
}

/* 
   Pack 'void *' into a string buffer.
*/
SWIGRUNTIME char *
SWIG_PackVoidPtr(char *buff, void *ptr, const char *name, size_t bsz) {
  char *r = buff;
  if ((2*sizeof(void *) + 2) > bsz) return 0;
  *(r++) = '_';
  r = SWIG_PackData(r,&ptr,sizeof(void *));
  if (strlen(name) + 1 > (bsz - (r - buff))) return 0;
  strcpy(r,name);
  return buff;
}

SWIGRUNTIME const char *
SWIG_UnpackVoidPtr(const char *c, void **ptr, const char *name) {
  if (*c != '_') {
    if (strcmp(c,"NULL") == 0) {
      *ptr = (void *) 0;
      return name;
    } else {
      return 0;
    }
  }
  return SWIG_UnpackData(++c,ptr,sizeof(void *));
}

SWIGRUNTIME char *
SWIG_PackDataName(char *buff, void *ptr, size_t sz, const char *name, size_t bsz) {
  char *r = buff;
  size_t lname = (name ? strlen(name) : 0);
  if ((2*sz + 2 + lname) > bsz) return 0;
  *(r++) = '_';
  r = SWIG_PackData(r,ptr,sz);
  if (lname) {
    strncpy(r,name,lname+1);
  } else {
    *r = 0;
  }
  return buff;
}

SWIGRUNTIME const char *
SWIG_UnpackDataName(const char *c, void *ptr, size_t sz, const char *name) {
  if (*c != '_') {
    if (strcmp(c,"NULL") == 0) {
      memset(ptr,0,sz);
      return name;
    } else {
      return 0;
    }
  }
  return SWIG_UnpackData(++c,ptr,sz);
}

#ifdef __cplusplus
}
#endif

/***********************************************************************
 * common.swg
 *
 *     This file contains generic SWIG runtime support for pointer
 *     type checking as well as a few commonly used macros to control
 *     external linkage.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 *
 * Copyright (c) 1999-2000, The University of Chicago
 * 
 * This file may be freely redistributed without license or fee provided
 * this copyright message remains intact.
 ************************************************************************/


#if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#  if !defined(STATIC_LINKED)
#    define SWIGEXPORT(a) __declspec(dllexport) a
#  else
#    define SWIGEXPORT(a) a
#  endif
#else
#  define SWIGEXPORT(a) a
#endif

#ifdef __cplusplus
extern "C" {
#endif


/*************************************************************************/


/* The static type info list */

static swig_type_info *swig_type_list = 0;
static swig_type_info **swig_type_list_handle = &swig_type_list;
  

/* Register a type mapping with the type-checking */
static swig_type_info *
SWIG_TypeRegister(swig_type_info *ti) {
  return SWIG_TypeRegisterTL(swig_type_list_handle, ti);
}

/* Search for a swig_type_info structure */
static swig_type_info *
SWIG_TypeQuery(const char *name) {
  return SWIG_TypeQueryTL(*swig_type_list_handle, name);
}

/* Set the clientdata field for a type */
static void
SWIG_TypeClientData(swig_type_info *ti, void *clientdata) {
  SWIG_TypeClientDataTL(*swig_type_list_handle, ti, clientdata);
}

/* This function will propagate the clientdata field of type to
* any new swig_type_info structures that have been added into the list
* of equivalent types.  It is like calling
* SWIG_TypeClientData(type, clientdata) a second time.
*/
static void
SWIG_PropagateClientData(swig_type_info *type) {
  SWIG_PropagateClientDataTL(*swig_type_list_handle, type);
}

#ifdef __cplusplus
}
#endif

/*
 * php4.swg
 *
 * PHP4 runtime library
 *
 */

#ifdef __cplusplus
extern "C" {
#endif
#include "zend.h"
#include "zend_API.h"
#include "php.h"

/* These TSRMLS_ stuff should already be defined now, but with older php under
   redhat are not... */
#ifndef TSRMLS_D
#define TSRMLS_D
#endif
#ifndef TSRMLS_DC
#define TSRMLS_DC
#endif
#ifndef TSRMLS_C
#define TSRMLS_C
#endif
#ifndef TSRMLS_CC
#define TSRMLS_CC
#endif

#ifdef __cplusplus
}
#endif

/* used to wrap returned objects in so we know whether they are newobject
   and need freeing, or not */
typedef struct _swig_object_wrapper {
  void * ptr;
  int newobject;
} swig_object_wrapper;

/* local scope self_constructors are set to 1 inside function wrappers
   which are also class constructors, so that the php4.swg output typemaps
   know whether or not to wrap returned objects in this_ptr or a new object */
int self_constructor=0;

/* empty zend destructor for types without one */
static ZEND_RSRC_DTOR_FUNC(SWIG_landfill) {};

/* This one makes old swig style string pointers but the php module doesn't
   use these any more.  This is just left here for old times sake and may go */
static void
SWIG_MakePtr(char *c, void *ptr, swig_type_info *ty) {
  static char hex[17] = "0123456789abcdef";
  unsigned long p, s;
  char data[32], *r;

  r = data;
  p = (unsigned long) ptr;
  if (p > 0) {
    while (p > 0) {
      s = p & 0xf;
      *(r++) = hex[s];
      p = p >> 4;
    }
    *r = '_';
    while (r >= data) {
      *(c++) = *(r--);
    }
    strcpy (c, ty->name);
  } else {
    strcpy (c, "NULL");
  }
}

static void
SWIG_SetPointerChar(char **c, void *ptr, swig_type_info *type) {
   char data[512];

   SWIG_MakePtr(data, ptr, type);
   *c = estrdup(data);
}

#define SWIG_SetPointerZval(a,b,c,d) SWIG_ZTS_SetPointerZval(a,b,c,d, SWIG_module_entry TSRMLS_CC)

static void
SWIG_ZTS_SetPointerZval(zval *z, void *ptr, swig_type_info *type, int newobject, zend_module_entry* module_entry TSRMLS_DC) {
  swig_object_wrapper *value=NULL;
  /* No need to call SWIG_MakePtr here! */
  if (type->clientdata) {
    if (! (*(int *)(type->clientdata))) zend_error(E_ERROR, "Type: %s failed to register with zend",type->name);
    value=(swig_object_wrapper *)emalloc(sizeof(swig_object_wrapper));
    value->ptr=ptr;
    value->newobject=newobject;
    ZEND_REGISTER_RESOURCE(z, value, *(int *)(type->clientdata));
    return;
  } else { /* have to deal with old fashioned string pointer?
              but this should not get this far */
    zend_error(E_ERROR, "Type: %s not registered with zend",type->name);
  }
}

/* This old-style routine converts an old string-pointer c into a real pointer
   ptr calling making appropriate casting functions according to ty
   We don't use this any more */
static int
SWIG_ConvertPtr_(char *c, void **ptr, swig_type_info *ty) {
   register int d;
   unsigned long p;
   swig_type_info *tc;

   if(c == NULL) {
   	*ptr = 0;
	return 0;
   }

   p = 0;
   if (*c != '_') {
    *ptr = (void *) 0;
    if (strcmp(c,"NULL") == 0) {
	return 0;
    } else {
	goto type_error;
    }
  }

    c++;
    /* Extract hex value from pointer */
    while ((d = *c)) {
      if ((d >= '0') && (d <= '9'))
        p = (p << 4) + (d - '0');
      else if ((d >= 'a') && (d <= 'f'))
        p = (p << 4) + (d - ('a'-10));
      else
        break;
      c++;
    }
    *ptr = (void *) p;
	
    if(ty) {
	tc = SWIG_TypeCheck(c,ty);
	if(!tc) goto type_error;
	*ptr = SWIG_TypeCast(tc, (void*)p);
    }
    return 0;

type_error:

    return -1;
}

/* This is a new pointer conversion routine
   Taking the native pointer p (which would have been converted from the old
   string pointer) and it's php type id, and it's type name (which also would
   have come from the old string pointer) it converts it to ptr calling 
   appropriate casting functions according to ty
   Sadly PHP has no API to find a type name from a type id, only from an instance
   of a resource of the type id, so we have to pass type_name as well.
   The two functions which might call this are:
   SWIG_ZTS_ConvertResourcePtr which gets the type name from the resource
   and the registered zend destructors for which we have one per type each
   with the type name hard wired in. */
static int
SWIG_ZTS_ConvertResourceData(void * p, int type, const char *type_name, void **ptr, swig_type_info *ty TSRMLS_DC) {
  swig_type_info *tc;

  if (ty) {
    if (! type_name) {  
      /* can't convert p to ptr type ty if we don't know what type p is */
      return -1;
    } else {
      /* convert and cast p from type_name to ptr as ty
         Need to sort out const-ness, can SWIG_TypeCast really not take a const? */
      tc = SWIG_TypeCheck((char *)type_name,ty);
      if (!tc) return -1;
      *ptr = SWIG_TypeCast(tc, (void*)p);
    }
  } else {
    /* They don't care about the target type, so just pass on the pointer! */
    *ptr = (void *) p;
  }
  return 0;
}

/* This function fills ptr with a pointer of type ty by extracting the pointer
   and type info from the resource in z.  z must be a resource
   It uses SWIG_ZTS_ConvertResourceData to do the real work. */
static int
SWIG_ZTS_ConvertResourcePtr(zval *z, void **ptr, swig_type_info *ty TSRMLS_DC) {
  swig_object_wrapper *value;
  void *p;
  int type;
  char *type_name;

  value = (swig_object_wrapper *) zend_list_find(z->value.lval,&type);
  p = value->ptr;
  if (type==-1) return -1;

  type_name=zend_rsrc_list_get_rsrc_type(z->value.lval);

  return SWIG_ZTS_ConvertResourceData(p,type,type_name,ptr,ty TSRMLS_CC);
}

/* But in fact SWIG_ConvertPtr is the native interface for getting typed
   pointer values out of zvals.  We need the TSRMLS_ macros for when we
   make PHP type calls later as we handle php resources */
#define SWIG_ConvertPtr(a,b,c) SWIG_ZTS_ConvertPtr(a,b,c TSRMLS_CC)

/* We allow passing of a STRING or RESOURCE pointing to the object
   or an OBJECT whose _cPtr is a string or resource pointing to the object
   STRING pointers are very depracated */
static int
SWIG_ZTS_ConvertPtr(zval *z, void **ptr, swig_type_info *ty TSRMLS_DC) {
   char *c;
   zval *val;
   
   if(z == NULL) {
	*ptr = 0;
	return 0;
   }

   if (z->type==IS_OBJECT) {
     zval ** _cPtr;
     if (zend_hash_find(HASH_OF(z),"_cPtr",sizeof("_cPtr"),(void**)&_cPtr)==SUCCESS) {
       /* Don't co-erce to string if it isn't */
       if ((*_cPtr)->type==IS_STRING) c = Z_STRVAL_PP(_cPtr);
       else if ((*_cPtr)->type==IS_RESOURCE) {
         return SWIG_ZTS_ConvertResourcePtr(*_cPtr,ptr,ty TSRMLS_CC);
       } else goto type_error; /* _cPtr was not string or resource property */
     } else goto type_error; /* can't find property _cPtr */
   } else if (z->type==IS_RESOURCE) {
     return SWIG_ZTS_ConvertResourcePtr(z,ptr,ty TSRMLS_CC);
   } else if (z->type==IS_STRING) {
     c = Z_STRVAL_P(z); 
     return SWIG_ConvertPtr_(c,ptr,ty);
   } else goto type_error;

type_error:

    return -1;
}


/* -------- TYPES TABLE (BEGIN) -------- */

#define  SWIGTYPE_p_lwes_event_type_db swig_types[0] 
#define  SWIGTYPE_p_in_addr swig_types[1] 
#define  SWIGTYPE_p_lwes_emitter swig_types[2] 
#define  SWIGTYPE_p_p_char swig_types[3] 
#define  SWIGTYPE_p_lwes_event swig_types[4] 
#define  SWIGTYPE_p_unsigned_int swig_types[5] 
#define  SWIGTYPE_p_unsigned_short swig_types[6] 
#define  SWIGTYPE_p_short swig_types[7] 
#define  SWIGTYPE_p_int swig_types[8] 
static swig_type_info *swig_types[10];

/* -------- TYPES TABLE (END) -------- */

/* header section */
/*
  +----------------------------------------------------------------------+
  | PHP version 4.0                                                      |
  +----------------------------------------------------------------------+
  | Copyright (c) 1997, 1998, 1999, 2000, 2001 The PHP Group             |
  +----------------------------------------------------------------------+
  | This source file is subject to version 2.02 of the PHP license,      |
  | that is bundled with this package in the file LICENSE, and is        |
  | available at through the world-wide-web at                           |
  | http://www.php.net/license/2_02.txt.                                 |
  | If you did not receive a copy of the PHP license and are unable to   |
  | obtain it through the world-wide-web, please send a note to          |
  | license@php.net so we can mail you a copy immediately.               |
  +----------------------------------------------------------------------+
  | Authors:                                                             |
  |                                                                      |
  +----------------------------------------------------------------------+
 */
#define SWIG_init	initlwes

#define SWIG_name	"lwes"
#ifdef __cplusplus
extern "C" {
#endif
#include "php.h"
#include "php_ini.h"
#include "ext/standard/info.h"
#include "php_lwes.h"
#ifdef __cplusplus
}
#endif


#include "lwes.h"



struct lwes_event *
lwes_event_create_no_db(char *event_name)
{
  return lwes_event_create(NULL, event_name);
}


/* class entry subsection */


/* entry subsection */
/* Every non-class user visible function must have an entry here */
function_entry lwes_functions[] = {
	ZEND_NAMED_FE(lwes_event_type_db_create,
		_wrap_lwes_event_type_db_create, NULL)
	ZEND_NAMED_FE(lwes_event_type_db_destroy,
		_wrap_lwes_event_type_db_destroy, NULL)
	ZEND_NAMED_FE(lwes_emitter_create,
		_wrap_lwes_emitter_create, NULL)
	ZEND_NAMED_FE(lwes_emitter_create_with_ttl,
		_wrap_lwes_emitter_create_with_ttl, NULL)
	ZEND_NAMED_FE(lwes_emitter_emit,
		_wrap_lwes_emitter_emit, NULL)
	ZEND_NAMED_FE(lwes_emitter_emitto,
		_wrap_lwes_emitter_emitto, NULL)
	ZEND_NAMED_FE(lwes_emitter_destroy,
		_wrap_lwes_emitter_destroy, NULL)
	ZEND_NAMED_FE(lwes_event_create,
		_wrap_lwes_event_create, NULL)
	ZEND_NAMED_FE(lwes_event_create_with_encoding,
		_wrap_lwes_event_create_with_encoding, NULL)
	ZEND_NAMED_FE(lwes_event_set_u_int_16,
		_wrap_lwes_event_set_U_INT_16, NULL)
	ZEND_NAMED_FE(lwes_event_get_u_int_16,
		_wrap_lwes_event_get_U_INT_16, NULL)
	ZEND_NAMED_FE(lwes_event_set_int_16,
		_wrap_lwes_event_set_INT_16, NULL)
	ZEND_NAMED_FE(lwes_event_get_int_16,
		_wrap_lwes_event_get_INT_16, NULL)
	ZEND_NAMED_FE(lwes_event_set_u_int_32,
		_wrap_lwes_event_set_U_INT_32, NULL)
	ZEND_NAMED_FE(lwes_event_get_u_int_32,
		_wrap_lwes_event_get_U_INT_32, NULL)
	ZEND_NAMED_FE(lwes_event_set_int_32,
		_wrap_lwes_event_set_INT_32, NULL)
	ZEND_NAMED_FE(lwes_event_get_int_32,
		_wrap_lwes_event_get_INT_32, NULL)
	ZEND_NAMED_FE(lwes_event_set_string,
		_wrap_lwes_event_set_STRING, NULL)
	ZEND_NAMED_FE(lwes_event_get_string,
		_wrap_lwes_event_get_STRING, NULL)
	ZEND_NAMED_FE(lwes_event_set_ip_addr_w_string,
		_wrap_lwes_event_set_IP_ADDR_w_string, NULL)
	ZEND_NAMED_FE(lwes_event_get_ip_addr,
		_wrap_lwes_event_get_IP_ADDR, NULL)
	ZEND_NAMED_FE(lwes_event_set_boolean,
		_wrap_lwes_event_set_BOOLEAN, NULL)
	ZEND_NAMED_FE(lwes_event_get_boolean,
		_wrap_lwes_event_get_BOOLEAN, NULL)
	ZEND_NAMED_FE(lwes_event_destroy,
		_wrap_lwes_event_destroy, NULL)
	ZEND_NAMED_FE(lwes_event_create_no_db,
		_wrap_lwes_event_create_no_db, NULL)
	{NULL, NULL, NULL}
};

zend_module_entry lwes_module_entry = {
#if ZEND_MODULE_API_NO > 20010900
    STANDARD_MODULE_HEADER,
#endif
    "lwes",
    lwes_functions,
    PHP_MINIT(lwes),
    PHP_MSHUTDOWN(lwes),
    PHP_RINIT(lwes),
    PHP_RSHUTDOWN(lwes),
    PHP_MINFO(lwes),
#if ZEND_MODULE_API_NO > 20010900
    NO_VERSION_YET,
#endif
    STANDARD_MODULE_PROPERTIES
};
zend_module_entry* SWIG_module_entry = &lwes_module_entry;


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (BEGIN) -------- */

static swig_type_info _swigt__p_lwes_event_type_db[] = {{"_p_lwes_event_type_db", 0, "struct lwes_event_type_db *", 0, 0, 0, 0},{"_p_lwes_event_type_db", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_in_addr[] = {{"_p_in_addr", 0, "struct in_addr *", 0, 0, 0, 0},{"_p_in_addr", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_lwes_emitter[] = {{"_p_lwes_emitter", 0, "struct lwes_emitter *", 0, 0, 0, 0},{"_p_lwes_emitter", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_p_char[] = {{"_p_p_char", 0, "char **", 0, 0, 0, 0},{"_p_p_char", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_lwes_event[] = {{"_p_lwes_event", 0, "struct lwes_event *", 0, 0, 0, 0},{"_p_lwes_event", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_unsigned_int[] = {{"_p_unsigned_int", 0, "unsigned int *", 0, 0, 0, 0},{"_p_unsigned_int", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_unsigned_short[] = {{"_p_unsigned_short", 0, "unsigned short *", 0, 0, 0, 0},{"_p_unsigned_short", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_short[] = {{"_p_short", 0, "short *", 0, 0, 0, 0},{"_p_short", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_int[] = {{"_p_int", 0, "int *", 0, 0, 0, 0},{"_p_int", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};

static swig_type_info *swig_types_initial[] = {
_swigt__p_lwes_event_type_db, 
_swigt__p_in_addr, 
_swigt__p_lwes_emitter, 
_swigt__p_p_char, 
_swigt__p_lwes_event, 
_swigt__p_unsigned_int, 
_swigt__p_unsigned_short, 
_swigt__p_short, 
_swigt__p_int, 
0
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (END) -------- */

/* vdecl subsection */
static int le_swig__p_lwes_event_type_db=0; /* handle for  */
static int le_swig__p_in_addr=0; /* handle for  */
static int le_swig__p_lwes_emitter=0; /* handle for  */
static int le_swig__p_p_char=0; /* handle for  */
static int le_swig__p_lwes_event=0; /* handle for  */
static int le_swig__p_unsigned_int=0; /* handle for  */
static int le_swig__p_unsigned_short=0; /* handle for  */
static int le_swig__p_short=0; /* handle for  */
static int le_swig__p_int=0; /* handle for  */
/* end vdecl subsection */
/* wrapper section */
ZEND_NAMED_FUNCTION(_wrap_lwes_event_type_db_create) {
    char *arg1 = (char *) 0 ;
    struct lwes_event_type_db *result;
    zval **args[2];
    int argbase=0 ;
    
    if (this_ptr && this_ptr->type==IS_OBJECT) {
        /* fake this_ptr as first arg (till we can work out how to do it better */
        argbase++;
    }
    if(((ZEND_NUM_ARGS() + argbase )!= 1) || (zend_get_parameters_array_ex(1-argbase, args)!= SUCCESS)) {
        WRONG_PARAM_COUNT;
    }
    
    {
        if ((*((0<argbase)?(&this_ptr):(args[0-argbase])))->type == IS_NULL) {
            arg1 = NULL;
        } else {
            convert_to_string_ex(((0<argbase)?(&this_ptr):(args[0-argbase])));
            arg1 = Z_STRVAL_PP(((0<argbase)?(&this_ptr):(args[0-argbase])));
        }
        
    }
    result = (struct lwes_event_type_db *)lwes_event_type_db_create(arg1);
    
    
    SWIG_SetPointerZval(return_value, (void *)result, SWIGTYPE_p_lwes_event_type_db, 0);
    
}


ZEND_NAMED_FUNCTION(_wrap_lwes_event_type_db_destroy) {
    struct lwes_event_type_db *arg1 = (struct lwes_event_type_db *) 0 ;
    int result;
    zval **args[2];
    int argbase=0 ;
    
    if (this_ptr && this_ptr->type==IS_OBJECT) {
        /* fake this_ptr as first arg (till we can work out how to do it better */
        argbase++;
    }
    if(((ZEND_NUM_ARGS() + argbase )!= 1) || (zend_get_parameters_array_ex(1-argbase, args)!= SUCCESS)) {
        WRONG_PARAM_COUNT;
    }
    
    {
        if ((*((0<argbase)?(&this_ptr):(args[0-argbase])))->type == IS_NULL) {
            arg1 = NULL;
        } else {
            if(SWIG_ConvertPtr(*((0<argbase)?(&this_ptr):(args[0-argbase])), (void **)&arg1, SWIGTYPE_p_lwes_event_type_db) < 0) {
                arg1 = NULL;
            }
        }
        
    }
    result = (int)lwes_event_type_db_destroy(arg1);
    
    
    ZVAL_LONG(return_value,result);
    
}


ZEND_NAMED_FUNCTION(_wrap_lwes_emitter_create) {
    char *arg1 = (char *) 0 ;
    char *arg2 = (char *) 0 ;
    int arg3 ;
    int arg4 ;
    short arg5 ;
    struct lwes_emitter *result;
    zval **args[6];
    int argbase=0 ;
    
    if (this_ptr && this_ptr->type==IS_OBJECT) {
        /* fake this_ptr as first arg (till we can work out how to do it better */
        argbase++;
    }
    if(((ZEND_NUM_ARGS() + argbase )!= 5) || (zend_get_parameters_array_ex(5-argbase, args)!= SUCCESS)) {
        WRONG_PARAM_COUNT;
    }
    
    {
        if ((*((0<argbase)?(&this_ptr):(args[0-argbase])))->type == IS_NULL) {
            arg1 = NULL;
        } else {
            convert_to_string_ex(((0<argbase)?(&this_ptr):(args[0-argbase])));
            arg1 = Z_STRVAL_PP(((0<argbase)?(&this_ptr):(args[0-argbase])));
        }
        
    }
    {
        if ((*args[1-argbase])->type == IS_NULL) {
            arg2 = NULL;
        } else {
            convert_to_string_ex(args[1-argbase]);
            arg2 = Z_STRVAL_PP(args[1-argbase]);
        }
        
    }
    
    convert_to_long_ex(args[2-argbase]);
    arg3 = (int) Z_LVAL_PP(args[2-argbase]);
    
    
    convert_to_long_ex(args[3-argbase]);
    arg4 = (int) Z_LVAL_PP(args[3-argbase]);
    
    
    convert_to_long_ex(args[4-argbase]);
    arg5 = (short) Z_LVAL_PP(args[4-argbase]);
    
    result = (struct lwes_emitter *)lwes_emitter_create(arg1,arg2,arg3,arg4,arg5);
    
    
    SWIG_SetPointerZval(return_value, (void *)result, SWIGTYPE_p_lwes_emitter, 0);
    
}


ZEND_NAMED_FUNCTION(_wrap_lwes_emitter_create_with_ttl) {
    char *arg1 = (char *) 0 ;
    char *arg2 = (char *) 0 ;
    int arg3 ;
    int arg4 ;
    short arg5 ;
    int arg6 ;
    struct lwes_emitter *result;
    zval **args[7];
    int argbase=0 ;
    
    if (this_ptr && this_ptr->type==IS_OBJECT) {
        /* fake this_ptr as first arg (till we can work out how to do it better */
        argbase++;
    }
    if(((ZEND_NUM_ARGS() + argbase )!= 6) || (zend_get_parameters_array_ex(6-argbase, args)!= SUCCESS)) {
        WRONG_PARAM_COUNT;
    }
    
    {
        if ((*((0<argbase)?(&this_ptr):(args[0-argbase])))->type == IS_NULL) {
            arg1 = NULL;
        } else {
            convert_to_string_ex(((0<argbase)?(&this_ptr):(args[0-argbase])));
            arg1 = Z_STRVAL_PP(((0<argbase)?(&this_ptr):(args[0-argbase])));
        }
        
    }
    {
        if ((*args[1-argbase])->type == IS_NULL) {
            arg2 = NULL;
        } else {
            convert_to_string_ex(args[1-argbase]);
            arg2 = Z_STRVAL_PP(args[1-argbase]);
        }
        
    }
    
    convert_to_long_ex(args[2-argbase]);
    arg3 = (int) Z_LVAL_PP(args[2-argbase]);
    
    
    convert_to_long_ex(args[3-argbase]);
    arg4 = (int) Z_LVAL_PP(args[3-argbase]);
    
    
    convert_to_long_ex(args[4-argbase]);
    arg5 = (short) Z_LVAL_PP(args[4-argbase]);
    
    
    convert_to_long_ex(args[5-argbase]);
    arg6 = (int) Z_LVAL_PP(args[5-argbase]);
    
    result = (struct lwes_emitter *)lwes_emitter_create_with_ttl(arg1,arg2,arg3,arg4,arg5,arg6);
    
    
    SWIG_SetPointerZval(return_value, (void *)result, SWIGTYPE_p_lwes_emitter, 0);
    
}


ZEND_NAMED_FUNCTION(_wrap_lwes_emitter_emit) {
    struct lwes_emitter *arg1 = (struct lwes_emitter *) 0 ;
    struct lwes_event *arg2 = (struct lwes_event *) 0 ;
    int result;
    zval **args[3];
    int argbase=0 ;
    
    if (this_ptr && this_ptr->type==IS_OBJECT) {
        /* fake this_ptr as first arg (till we can work out how to do it better */
        argbase++;
    }
    if(((ZEND_NUM_ARGS() + argbase )!= 2) || (zend_get_parameters_array_ex(2-argbase, args)!= SUCCESS)) {
        WRONG_PARAM_COUNT;
    }
    
    
    if(SWIG_ConvertPtr(*((0<argbase)?(&this_ptr):(args[0-argbase])), (void **) &arg1, SWIGTYPE_p_lwes_emitter) < 0) {
        zend_error(E_ERROR, "Type error in argument %d of lwes_emitter_emit. Expected %s", 1-argbase, SWIGTYPE_p_lwes_emitter->name);
    }
    
    
    if(SWIG_ConvertPtr(*args[1-argbase], (void **) &arg2, SWIGTYPE_p_lwes_event) < 0) {
        zend_error(E_ERROR, "Type error in argument %d of lwes_emitter_emit. Expected %s", 2-argbase, SWIGTYPE_p_lwes_event->name);
    }
    
    result = (int)lwes_emitter_emit(arg1,arg2);
    
    
    ZVAL_LONG(return_value,result);
    
}


ZEND_NAMED_FUNCTION(_wrap_lwes_emitter_emitto) {
    char *arg1 = (char *) 0 ;
    char *arg2 = (char *) 0 ;
    int arg3 ;
    struct lwes_emitter *arg4 = (struct lwes_emitter *) 0 ;
    struct lwes_event *arg5 = (struct lwes_event *) 0 ;
    int result;
    zval **args[6];
    int argbase=0 ;
    
    if (this_ptr && this_ptr->type==IS_OBJECT) {
        /* fake this_ptr as first arg (till we can work out how to do it better */
        argbase++;
    }
    if(((ZEND_NUM_ARGS() + argbase )!= 5) || (zend_get_parameters_array_ex(5-argbase, args)!= SUCCESS)) {
        WRONG_PARAM_COUNT;
    }
    
    {
        if ((*((0<argbase)?(&this_ptr):(args[0-argbase])))->type == IS_NULL) {
            arg1 = NULL;
        } else {
            convert_to_string_ex(((0<argbase)?(&this_ptr):(args[0-argbase])));
            arg1 = Z_STRVAL_PP(((0<argbase)?(&this_ptr):(args[0-argbase])));
        }
        
    }
    {
        if ((*args[1-argbase])->type == IS_NULL) {
            arg2 = NULL;
        } else {
            convert_to_string_ex(args[1-argbase]);
            arg2 = Z_STRVAL_PP(args[1-argbase]);
        }
        
    }
    
    convert_to_long_ex(args[2-argbase]);
    arg3 = (int) Z_LVAL_PP(args[2-argbase]);
    
    
    if(SWIG_ConvertPtr(*args[3-argbase], (void **) &arg4, SWIGTYPE_p_lwes_emitter) < 0) {
        zend_error(E_ERROR, "Type error in argument %d of lwes_emitter_emitto. Expected %s", 4-argbase, SWIGTYPE_p_lwes_emitter->name);
    }
    
    
    if(SWIG_ConvertPtr(*args[4-argbase], (void **) &arg5, SWIGTYPE_p_lwes_event) < 0) {
        zend_error(E_ERROR, "Type error in argument %d of lwes_emitter_emitto. Expected %s", 5-argbase, SWIGTYPE_p_lwes_event->name);
    }
    
    result = (int)lwes_emitter_emitto(arg1,arg2,arg3,arg4,arg5);
    
    
    ZVAL_LONG(return_value,result);
    
}


ZEND_NAMED_FUNCTION(_wrap_lwes_emitter_destroy) {
    struct lwes_emitter *arg1 = (struct lwes_emitter *) 0 ;
    int result;
    zval **args[2];
    int argbase=0 ;
    
    if (this_ptr && this_ptr->type==IS_OBJECT) {
        /* fake this_ptr as first arg (till we can work out how to do it better */
        argbase++;
    }
    if(((ZEND_NUM_ARGS() + argbase )!= 1) || (zend_get_parameters_array_ex(1-argbase, args)!= SUCCESS)) {
        WRONG_PARAM_COUNT;
    }
    
    
    if(SWIG_ConvertPtr(*((0<argbase)?(&this_ptr):(args[0-argbase])), (void **) &arg1, SWIGTYPE_p_lwes_emitter) < 0) {
        zend_error(E_ERROR, "Type error in argument %d of lwes_emitter_destroy. Expected %s", 1-argbase, SWIGTYPE_p_lwes_emitter->name);
    }
    
    result = (int)lwes_emitter_destroy(arg1);
    
    
    ZVAL_LONG(return_value,result);
    
}


ZEND_NAMED_FUNCTION(_wrap_lwes_event_create) {
    struct lwes_event_type_db *arg1 = (struct lwes_event_type_db *) 0 ;
    char *arg2 = (char *) 0 ;
    struct lwes_event *result;
    zval **args[3];
    int argbase=0 ;
    
    if (this_ptr && this_ptr->type==IS_OBJECT) {
        /* fake this_ptr as first arg (till we can work out how to do it better */
        argbase++;
    }
    if(((ZEND_NUM_ARGS() + argbase )!= 2) || (zend_get_parameters_array_ex(2-argbase, args)!= SUCCESS)) {
        WRONG_PARAM_COUNT;
    }
    
    {
        if ((*((0<argbase)?(&this_ptr):(args[0-argbase])))->type == IS_NULL) {
            arg1 = NULL;
        } else {
            if(SWIG_ConvertPtr(*((0<argbase)?(&this_ptr):(args[0-argbase])), (void **)&arg1, SWIGTYPE_p_lwes_event_type_db) < 0) {
                arg1 = NULL;
            }
        }
        
    }
    {
        if ((*args[1-argbase])->type == IS_NULL) {
            arg2 = NULL;
        } else {
            convert_to_string_ex(args[1-argbase]);
            arg2 = Z_STRVAL_PP(args[1-argbase]);
        }
        
    }
    result = (struct lwes_event *)lwes_event_create(arg1,arg2);
    
    
    SWIG_SetPointerZval(return_value, (void *)result, SWIGTYPE_p_lwes_event, 0);
    
}


ZEND_NAMED_FUNCTION(_wrap_lwes_event_create_with_encoding) {
    struct lwes_event_type_db *arg1 = (struct lwes_event_type_db *) 0 ;
    char *arg2 = (char *) 0 ;
    short arg3 ;
    struct lwes_event *result;
    zval **args[4];
    int argbase=0 ;
    
    if (this_ptr && this_ptr->type==IS_OBJECT) {
        /* fake this_ptr as first arg (till we can work out how to do it better */
        argbase++;
    }
    if(((ZEND_NUM_ARGS() + argbase )!= 3) || (zend_get_parameters_array_ex(3-argbase, args)!= SUCCESS)) {
        WRONG_PARAM_COUNT;
    }
    
    {
        if ((*((0<argbase)?(&this_ptr):(args[0-argbase])))->type == IS_NULL) {
            arg1 = NULL;
        } else {
            if(SWIG_ConvertPtr(*((0<argbase)?(&this_ptr):(args[0-argbase])), (void **)&arg1, SWIGTYPE_p_lwes_event_type_db) < 0) {
                arg1 = NULL;
            }
        }
        
    }
    {
        if ((*args[1-argbase])->type == IS_NULL) {
            arg2 = NULL;
        } else {
            convert_to_string_ex(args[1-argbase]);
            arg2 = Z_STRVAL_PP(args[1-argbase]);
        }
        
    }
    
    convert_to_long_ex(args[2-argbase]);
    arg3 = (short) Z_LVAL_PP(args[2-argbase]);
    
    result = (struct lwes_event *)lwes_event_create_with_encoding(arg1,arg2,arg3);
    
    
    SWIG_SetPointerZval(return_value, (void *)result, SWIGTYPE_p_lwes_event, 0);
    
}


ZEND_NAMED_FUNCTION(_wrap_lwes_event_set_U_INT_16) {
    struct lwes_event *arg1 = (struct lwes_event *) 0 ;
    char *arg2 = (char *) 0 ;
    unsigned short arg3 ;
    int result;
    zval **args[4];
    int argbase=0 ;
    
    if (this_ptr && this_ptr->type==IS_OBJECT) {
        /* fake this_ptr as first arg (till we can work out how to do it better */
        argbase++;
    }
    if(((ZEND_NUM_ARGS() + argbase )!= 3) || (zend_get_parameters_array_ex(3-argbase, args)!= SUCCESS)) {
        WRONG_PARAM_COUNT;
    }
    
    
    if(SWIG_ConvertPtr(*((0<argbase)?(&this_ptr):(args[0-argbase])), (void **) &arg1, SWIGTYPE_p_lwes_event) < 0) {
        zend_error(E_ERROR, "Type error in argument %d of lwes_event_set_U_INT_16. Expected %s", 1-argbase, SWIGTYPE_p_lwes_event->name);
    }
    
    {
        if ((*args[1-argbase])->type == IS_NULL) {
            arg2 = NULL;
        } else {
            convert_to_string_ex(args[1-argbase]);
            arg2 = Z_STRVAL_PP(args[1-argbase]);
        }
        
    }
    
    convert_to_long_ex(args[2-argbase]);
    arg3 = (unsigned short) Z_LVAL_PP(args[2-argbase]);
    
    result = (int)lwes_event_set_U_INT_16(arg1,arg2,arg3);
    
    
    ZVAL_LONG(return_value,result);
    
}


ZEND_NAMED_FUNCTION(_wrap_lwes_event_get_U_INT_16) {
    struct lwes_event *arg1 = (struct lwes_event *) 0 ;
    char *arg2 = (char *) 0 ;
    unsigned short *arg3 = (unsigned short *) 0 ;
    int result;
    unsigned short intr3 ;
    int force3 ;
    zval **args[4];
    int argbase=0 ;
    zval ** _saved[1] ;
    
    if (this_ptr && this_ptr->type==IS_OBJECT) {
        /* fake this_ptr as first arg (till we can work out how to do it better */
        argbase++;
    }
    if(((ZEND_NUM_ARGS() + argbase )!= 3) || (zend_get_parameters_array_ex(3-argbase, args)!= SUCCESS)) {
        WRONG_PARAM_COUNT;
    }
    
    
    if(SWIG_ConvertPtr(*((0<argbase)?(&this_ptr):(args[0-argbase])), (void **) &arg1, SWIGTYPE_p_lwes_event) < 0) {
        zend_error(E_ERROR, "Type error in argument %d of lwes_event_get_U_INT_16. Expected %s", 1-argbase, SWIGTYPE_p_lwes_event->name);
    }
    
    {
        if ((*args[1-argbase])->type == IS_NULL) {
            arg2 = NULL;
        } else {
            convert_to_string_ex(args[1-argbase]);
            arg2 = Z_STRVAL_PP(args[1-argbase]);
        }
        
    }
    
    /* inout typemap for unsigned short using convert_to_long_ex and ZVAL_LONG */
    if(SWIG_ConvertPtr(*args[2-argbase], (void **) &arg3, SWIGTYPE_p_unsigned_short) < 0) {
        /* So... we didn't get a ref or ptr, but can it be reasonably 
               co-erced into what we were looking for a ref of or ptr to? */
        if (!PZVAL_IS_REF(*args[2-argbase]) && (*args[2-argbase])->type==IS_NULL) {
            // null passed not by reference means pass NULL
            arg3 = NULL;
            force3=0;
        } else if (PZVAL_IS_REF(*args[2-argbase]) &&
        ((*args[2-argbase])->type==IS_STRING ||
        (*args[2-argbase])->type==IS_LONG ||
        /* Null passed by reference means we want a value back */
        (*args[2-argbase])->type==IS_NULL ||
        (*args[2-argbase])->type==IS_BOOL ||
        (*args[2-argbase])->type==IS_DOUBLE)) {
            convert_to_long_ex(args[2-argbase]);
            intr3 = (unsigned short) (*args[2-argbase])->value.lval;
            arg3 = &intr3;
            /* have to passback arg$arg too */
            force3=1;
        } else {
            /* wasn't a pre/ref/thing, OR anything like an int thing */
            force3=0;
            zend_error(E_ERROR, "Type error in argument %d of lwes_event_get_U_INT_16. Expected %s or at least something looking vaguely like a number hopefully passed by reference", 3-argbase, SWIGTYPE_p_unsigned_short->name);
        }
    } else force3=0;
    
    _saved[0] = args[2-argbase];
    result = (int)lwes_event_get_U_INT_16(arg1,arg2,arg3);
    
    
    ZVAL_LONG(return_value,result);
    
    
    if (force3) {
        /* pass back arg3 through params (_saved[0]) if we can */
        if(! PZVAL_IS_REF(*_saved[0])) {
            zend_error(E_WARNING, "Parameter %d of lwes_event_get_U_INT_16 wasn't passed by reference [argout unsigned short *, unsigned short &]",3-argbase);
        } else {
            ZVAL_LONG(*_saved[0],intr3);	
        }
    }
    
}


ZEND_NAMED_FUNCTION(_wrap_lwes_event_set_INT_16) {
    struct lwes_event *arg1 = (struct lwes_event *) 0 ;
    char *arg2 = (char *) 0 ;
    short arg3 ;
    int result;
    zval **args[4];
    int argbase=0 ;
    
    if (this_ptr && this_ptr->type==IS_OBJECT) {
        /* fake this_ptr as first arg (till we can work out how to do it better */
        argbase++;
    }
    if(((ZEND_NUM_ARGS() + argbase )!= 3) || (zend_get_parameters_array_ex(3-argbase, args)!= SUCCESS)) {
        WRONG_PARAM_COUNT;
    }
    
    
    if(SWIG_ConvertPtr(*((0<argbase)?(&this_ptr):(args[0-argbase])), (void **) &arg1, SWIGTYPE_p_lwes_event) < 0) {
        zend_error(E_ERROR, "Type error in argument %d of lwes_event_set_INT_16. Expected %s", 1-argbase, SWIGTYPE_p_lwes_event->name);
    }
    
    {
        if ((*args[1-argbase])->type == IS_NULL) {
            arg2 = NULL;
        } else {
            convert_to_string_ex(args[1-argbase]);
            arg2 = Z_STRVAL_PP(args[1-argbase]);
        }
        
    }
    
    convert_to_long_ex(args[2-argbase]);
    arg3 = (short) Z_LVAL_PP(args[2-argbase]);
    
    result = (int)lwes_event_set_INT_16(arg1,arg2,arg3);
    
    
    ZVAL_LONG(return_value,result);
    
}


ZEND_NAMED_FUNCTION(_wrap_lwes_event_get_INT_16) {
    struct lwes_event *arg1 = (struct lwes_event *) 0 ;
    char *arg2 = (char *) 0 ;
    short *arg3 = (short *) 0 ;
    int result;
    short intr3 ;
    int force3 ;
    zval **args[4];
    int argbase=0 ;
    zval ** _saved[1] ;
    
    if (this_ptr && this_ptr->type==IS_OBJECT) {
        /* fake this_ptr as first arg (till we can work out how to do it better */
        argbase++;
    }
    if(((ZEND_NUM_ARGS() + argbase )!= 3) || (zend_get_parameters_array_ex(3-argbase, args)!= SUCCESS)) {
        WRONG_PARAM_COUNT;
    }
    
    
    if(SWIG_ConvertPtr(*((0<argbase)?(&this_ptr):(args[0-argbase])), (void **) &arg1, SWIGTYPE_p_lwes_event) < 0) {
        zend_error(E_ERROR, "Type error in argument %d of lwes_event_get_INT_16. Expected %s", 1-argbase, SWIGTYPE_p_lwes_event->name);
    }
    
    {
        if ((*args[1-argbase])->type == IS_NULL) {
            arg2 = NULL;
        } else {
            convert_to_string_ex(args[1-argbase]);
            arg2 = Z_STRVAL_PP(args[1-argbase]);
        }
        
    }
    
    /* inout typemap for short using convert_to_long_ex and ZVAL_LONG */
    if(SWIG_ConvertPtr(*args[2-argbase], (void **) &arg3, SWIGTYPE_p_short) < 0) {
        /* So... we didn't get a ref or ptr, but can it be reasonably 
               co-erced into what we were looking for a ref of or ptr to? */
        if (!PZVAL_IS_REF(*args[2-argbase]) && (*args[2-argbase])->type==IS_NULL) {
            // null passed not by reference means pass NULL
            arg3 = NULL;
            force3=0;
        } else if (PZVAL_IS_REF(*args[2-argbase]) &&
        ((*args[2-argbase])->type==IS_STRING ||
        (*args[2-argbase])->type==IS_LONG ||
        /* Null passed by reference means we want a value back */
        (*args[2-argbase])->type==IS_NULL ||
        (*args[2-argbase])->type==IS_BOOL ||
        (*args[2-argbase])->type==IS_DOUBLE)) {
            convert_to_long_ex(args[2-argbase]);
            intr3 = (short) (*args[2-argbase])->value.lval;
            arg3 = &intr3;
            /* have to passback arg$arg too */
            force3=1;
        } else {
            /* wasn't a pre/ref/thing, OR anything like an int thing */
            force3=0;
            zend_error(E_ERROR, "Type error in argument %d of lwes_event_get_INT_16. Expected %s or at least something looking vaguely like a number hopefully passed by reference", 3-argbase, SWIGTYPE_p_short->name);
        }
    } else force3=0;
    
    _saved[0] = args[2-argbase];
    result = (int)lwes_event_get_INT_16(arg1,arg2,arg3);
    
    
    ZVAL_LONG(return_value,result);
    
    
    if (force3) {
        /* pass back arg3 through params (_saved[0]) if we can */
        if(! PZVAL_IS_REF(*_saved[0])) {
            zend_error(E_WARNING, "Parameter %d of lwes_event_get_INT_16 wasn't passed by reference [argout short *, short &]",3-argbase);
        } else {
            ZVAL_LONG(*_saved[0],intr3);	
        }
    }
    
}


ZEND_NAMED_FUNCTION(_wrap_lwes_event_set_U_INT_32) {
    struct lwes_event *arg1 = (struct lwes_event *) 0 ;
    char *arg2 = (char *) 0 ;
    unsigned int arg3 ;
    int result;
    zval **args[4];
    int argbase=0 ;
    
    if (this_ptr && this_ptr->type==IS_OBJECT) {
        /* fake this_ptr as first arg (till we can work out how to do it better */
        argbase++;
    }
    if(((ZEND_NUM_ARGS() + argbase )!= 3) || (zend_get_parameters_array_ex(3-argbase, args)!= SUCCESS)) {
        WRONG_PARAM_COUNT;
    }
    
    
    if(SWIG_ConvertPtr(*((0<argbase)?(&this_ptr):(args[0-argbase])), (void **) &arg1, SWIGTYPE_p_lwes_event) < 0) {
        zend_error(E_ERROR, "Type error in argument %d of lwes_event_set_U_INT_32. Expected %s", 1-argbase, SWIGTYPE_p_lwes_event->name);
    }
    
    {
        if ((*args[1-argbase])->type == IS_NULL) {
            arg2 = NULL;
        } else {
            convert_to_string_ex(args[1-argbase]);
            arg2 = Z_STRVAL_PP(args[1-argbase]);
        }
        
    }
    
    convert_to_long_ex(args[2-argbase]);
    arg3 = (unsigned int) Z_LVAL_PP(args[2-argbase]);
    
    result = (int)lwes_event_set_U_INT_32(arg1,arg2,arg3);
    
    
    ZVAL_LONG(return_value,result);
    
}


ZEND_NAMED_FUNCTION(_wrap_lwes_event_get_U_INT_32) {
    struct lwes_event *arg1 = (struct lwes_event *) 0 ;
    char *arg2 = (char *) 0 ;
    unsigned int *arg3 = (unsigned int *) 0 ;
    int result;
    unsigned int intr3 ;
    int force3 ;
    zval **args[4];
    int argbase=0 ;
    zval ** _saved[1] ;
    
    if (this_ptr && this_ptr->type==IS_OBJECT) {
        /* fake this_ptr as first arg (till we can work out how to do it better */
        argbase++;
    }
    if(((ZEND_NUM_ARGS() + argbase )!= 3) || (zend_get_parameters_array_ex(3-argbase, args)!= SUCCESS)) {
        WRONG_PARAM_COUNT;
    }
    
    
    if(SWIG_ConvertPtr(*((0<argbase)?(&this_ptr):(args[0-argbase])), (void **) &arg1, SWIGTYPE_p_lwes_event) < 0) {
        zend_error(E_ERROR, "Type error in argument %d of lwes_event_get_U_INT_32. Expected %s", 1-argbase, SWIGTYPE_p_lwes_event->name);
    }
    
    {
        if ((*args[1-argbase])->type == IS_NULL) {
            arg2 = NULL;
        } else {
            convert_to_string_ex(args[1-argbase]);
            arg2 = Z_STRVAL_PP(args[1-argbase]);
        }
        
    }
    
    /* inout typemap for unsigned int using convert_to_long_ex and ZVAL_LONG */
    if(SWIG_ConvertPtr(*args[2-argbase], (void **) &arg3, SWIGTYPE_p_unsigned_int) < 0) {
        /* So... we didn't get a ref or ptr, but can it be reasonably 
               co-erced into what we were looking for a ref of or ptr to? */
        if (!PZVAL_IS_REF(*args[2-argbase]) && (*args[2-argbase])->type==IS_NULL) {
            // null passed not by reference means pass NULL
            arg3 = NULL;
            force3=0;
        } else if (PZVAL_IS_REF(*args[2-argbase]) &&
        ((*args[2-argbase])->type==IS_STRING ||
        (*args[2-argbase])->type==IS_LONG ||
        /* Null passed by reference means we want a value back */
        (*args[2-argbase])->type==IS_NULL ||
        (*args[2-argbase])->type==IS_BOOL ||
        (*args[2-argbase])->type==IS_DOUBLE)) {
            convert_to_long_ex(args[2-argbase]);
            intr3 = (unsigned int) (*args[2-argbase])->value.lval;
            arg3 = &intr3;
            /* have to passback arg$arg too */
            force3=1;
        } else {
            /* wasn't a pre/ref/thing, OR anything like an int thing */
            force3=0;
            zend_error(E_ERROR, "Type error in argument %d of lwes_event_get_U_INT_32. Expected %s or at least something looking vaguely like a number hopefully passed by reference", 3-argbase, SWIGTYPE_p_unsigned_int->name);
        }
    } else force3=0;
    
    _saved[0] = args[2-argbase];
    result = (int)lwes_event_get_U_INT_32(arg1,arg2,arg3);
    
    
    ZVAL_LONG(return_value,result);
    
    
    if (force3) {
        /* pass back arg3 through params (_saved[0]) if we can */
        if(! PZVAL_IS_REF(*_saved[0])) {
            zend_error(E_WARNING, "Parameter %d of lwes_event_get_U_INT_32 wasn't passed by reference [argout unsigned int *, unsigned int &]",3-argbase);
        } else {
            ZVAL_LONG(*_saved[0],intr3);	
        }
    }
    
}


ZEND_NAMED_FUNCTION(_wrap_lwes_event_set_INT_32) {
    struct lwes_event *arg1 = (struct lwes_event *) 0 ;
    char *arg2 = (char *) 0 ;
    int arg3 ;
    int result;
    zval **args[4];
    int argbase=0 ;
    
    if (this_ptr && this_ptr->type==IS_OBJECT) {
        /* fake this_ptr as first arg (till we can work out how to do it better */
        argbase++;
    }
    if(((ZEND_NUM_ARGS() + argbase )!= 3) || (zend_get_parameters_array_ex(3-argbase, args)!= SUCCESS)) {
        WRONG_PARAM_COUNT;
    }
    
    
    if(SWIG_ConvertPtr(*((0<argbase)?(&this_ptr):(args[0-argbase])), (void **) &arg1, SWIGTYPE_p_lwes_event) < 0) {
        zend_error(E_ERROR, "Type error in argument %d of lwes_event_set_INT_32. Expected %s", 1-argbase, SWIGTYPE_p_lwes_event->name);
    }
    
    {
        if ((*args[1-argbase])->type == IS_NULL) {
            arg2 = NULL;
        } else {
            convert_to_string_ex(args[1-argbase]);
            arg2 = Z_STRVAL_PP(args[1-argbase]);
        }
        
    }
    
    convert_to_long_ex(args[2-argbase]);
    arg3 = (int) Z_LVAL_PP(args[2-argbase]);
    
    result = (int)lwes_event_set_INT_32(arg1,arg2,arg3);
    
    
    ZVAL_LONG(return_value,result);
    
}


ZEND_NAMED_FUNCTION(_wrap_lwes_event_get_INT_32) {
    struct lwes_event *arg1 = (struct lwes_event *) 0 ;
    char *arg2 = (char *) 0 ;
    int *arg3 = (int *) 0 ;
    int result;
    int intr3 ;
    int force3 ;
    zval **args[4];
    int argbase=0 ;
    zval ** _saved[1] ;
    
    if (this_ptr && this_ptr->type==IS_OBJECT) {
        /* fake this_ptr as first arg (till we can work out how to do it better */
        argbase++;
    }
    if(((ZEND_NUM_ARGS() + argbase )!= 3) || (zend_get_parameters_array_ex(3-argbase, args)!= SUCCESS)) {
        WRONG_PARAM_COUNT;
    }
    
    
    if(SWIG_ConvertPtr(*((0<argbase)?(&this_ptr):(args[0-argbase])), (void **) &arg1, SWIGTYPE_p_lwes_event) < 0) {
        zend_error(E_ERROR, "Type error in argument %d of lwes_event_get_INT_32. Expected %s", 1-argbase, SWIGTYPE_p_lwes_event->name);
    }
    
    {
        if ((*args[1-argbase])->type == IS_NULL) {
            arg2 = NULL;
        } else {
            convert_to_string_ex(args[1-argbase]);
            arg2 = Z_STRVAL_PP(args[1-argbase]);
        }
        
    }
    
    /* inout typemap for int using convert_to_long_ex and ZVAL_LONG */
    if(SWIG_ConvertPtr(*args[2-argbase], (void **) &arg3, SWIGTYPE_p_int) < 0) {
        /* So... we didn't get a ref or ptr, but can it be reasonably 
               co-erced into what we were looking for a ref of or ptr to? */
        if (!PZVAL_IS_REF(*args[2-argbase]) && (*args[2-argbase])->type==IS_NULL) {
            // null passed not by reference means pass NULL
            arg3 = NULL;
            force3=0;
        } else if (PZVAL_IS_REF(*args[2-argbase]) &&
        ((*args[2-argbase])->type==IS_STRING ||
        (*args[2-argbase])->type==IS_LONG ||
        /* Null passed by reference means we want a value back */
        (*args[2-argbase])->type==IS_NULL ||
        (*args[2-argbase])->type==IS_BOOL ||
        (*args[2-argbase])->type==IS_DOUBLE)) {
            convert_to_long_ex(args[2-argbase]);
            intr3 = (int) (*args[2-argbase])->value.lval;
            arg3 = &intr3;
            /* have to passback arg$arg too */
            force3=1;
        } else {
            /* wasn't a pre/ref/thing, OR anything like an int thing */
            force3=0;
            zend_error(E_ERROR, "Type error in argument %d of lwes_event_get_INT_32. Expected %s or at least something looking vaguely like a number hopefully passed by reference", 3-argbase, SWIGTYPE_p_int->name);
        }
    } else force3=0;
    
    _saved[0] = args[2-argbase];
    result = (int)lwes_event_get_INT_32(arg1,arg2,arg3);
    
    
    ZVAL_LONG(return_value,result);
    
    
    if (force3) {
        /* pass back arg3 through params (_saved[0]) if we can */
        if(! PZVAL_IS_REF(*_saved[0])) {
            zend_error(E_WARNING, "Parameter %d of lwes_event_get_INT_32 wasn't passed by reference [argout int *, int &]",3-argbase);
        } else {
            ZVAL_LONG(*_saved[0],intr3);	
        }
    }
    
}


ZEND_NAMED_FUNCTION(_wrap_lwes_event_set_STRING) {
    struct lwes_event *arg1 = (struct lwes_event *) 0 ;
    char *arg2 = (char *) 0 ;
    char *arg3 = (char *) 0 ;
    int result;
    zval **args[4];
    int argbase=0 ;
    
    if (this_ptr && this_ptr->type==IS_OBJECT) {
        /* fake this_ptr as first arg (till we can work out how to do it better */
        argbase++;
    }
    if(((ZEND_NUM_ARGS() + argbase )!= 3) || (zend_get_parameters_array_ex(3-argbase, args)!= SUCCESS)) {
        WRONG_PARAM_COUNT;
    }
    
    
    if(SWIG_ConvertPtr(*((0<argbase)?(&this_ptr):(args[0-argbase])), (void **) &arg1, SWIGTYPE_p_lwes_event) < 0) {
        zend_error(E_ERROR, "Type error in argument %d of lwes_event_set_STRING. Expected %s", 1-argbase, SWIGTYPE_p_lwes_event->name);
    }
    
    {
        if ((*args[1-argbase])->type == IS_NULL) {
            arg2 = NULL;
        } else {
            convert_to_string_ex(args[1-argbase]);
            arg2 = Z_STRVAL_PP(args[1-argbase]);
        }
        
    }
    {
        if ((*args[2-argbase])->type == IS_NULL) {
            arg3 = NULL;
        } else {
            convert_to_string_ex(args[2-argbase]);
            arg3 = Z_STRVAL_PP(args[2-argbase]);
        }
        
    }
    result = (int)lwes_event_set_STRING(arg1,arg2,arg3);
    
    
    ZVAL_LONG(return_value,result);
    
}


ZEND_NAMED_FUNCTION(_wrap_lwes_event_get_STRING) {
    struct lwes_event *arg1 = (struct lwes_event *) 0 ;
    char *arg2 = (char *) 0 ;
    char **arg3 = (char **) 0 ;
    int result;
    zval **args[4];
    int argbase=0 ;
    
    if (this_ptr && this_ptr->type==IS_OBJECT) {
        /* fake this_ptr as first arg (till we can work out how to do it better */
        argbase++;
    }
    if(((ZEND_NUM_ARGS() + argbase )!= 3) || (zend_get_parameters_array_ex(3-argbase, args)!= SUCCESS)) {
        WRONG_PARAM_COUNT;
    }
    
    
    if(SWIG_ConvertPtr(*((0<argbase)?(&this_ptr):(args[0-argbase])), (void **) &arg1, SWIGTYPE_p_lwes_event) < 0) {
        zend_error(E_ERROR, "Type error in argument %d of lwes_event_get_STRING. Expected %s", 1-argbase, SWIGTYPE_p_lwes_event->name);
    }
    
    {
        if ((*args[1-argbase])->type == IS_NULL) {
            arg2 = NULL;
        } else {
            convert_to_string_ex(args[1-argbase]);
            arg2 = Z_STRVAL_PP(args[1-argbase]);
        }
        
    }
    
    if(SWIG_ConvertPtr(*args[2-argbase], (void **) &arg3, SWIGTYPE_p_p_char) < 0) {
        zend_error(E_ERROR, "Type error in argument %d of lwes_event_get_STRING. Expected %s", 3-argbase, SWIGTYPE_p_p_char->name);
    }
    
    result = (int)lwes_event_get_STRING(arg1,arg2,arg3);
    
    
    ZVAL_LONG(return_value,result);
    
}


ZEND_NAMED_FUNCTION(_wrap_lwes_event_set_IP_ADDR_w_string) {
    struct lwes_event *arg1 = (struct lwes_event *) 0 ;
    char *arg2 = (char *) 0 ;
    char *arg3 = (char *) 0 ;
    int result;
    zval **args[4];
    int argbase=0 ;
    
    if (this_ptr && this_ptr->type==IS_OBJECT) {
        /* fake this_ptr as first arg (till we can work out how to do it better */
        argbase++;
    }
    if(((ZEND_NUM_ARGS() + argbase )!= 3) || (zend_get_parameters_array_ex(3-argbase, args)!= SUCCESS)) {
        WRONG_PARAM_COUNT;
    }
    
    
    if(SWIG_ConvertPtr(*((0<argbase)?(&this_ptr):(args[0-argbase])), (void **) &arg1, SWIGTYPE_p_lwes_event) < 0) {
        zend_error(E_ERROR, "Type error in argument %d of lwes_event_set_IP_ADDR_w_string. Expected %s", 1-argbase, SWIGTYPE_p_lwes_event->name);
    }
    
    {
        if ((*args[1-argbase])->type == IS_NULL) {
            arg2 = NULL;
        } else {
            convert_to_string_ex(args[1-argbase]);
            arg2 = Z_STRVAL_PP(args[1-argbase]);
        }
        
    }
    {
        if ((*args[2-argbase])->type == IS_NULL) {
            arg3 = NULL;
        } else {
            convert_to_string_ex(args[2-argbase]);
            arg3 = Z_STRVAL_PP(args[2-argbase]);
        }
        
    }
    result = (int)lwes_event_set_IP_ADDR_w_string(arg1,arg2,arg3);
    
    
    ZVAL_LONG(return_value,result);
    
}


ZEND_NAMED_FUNCTION(_wrap_lwes_event_get_IP_ADDR) {
    struct lwes_event *arg1 = (struct lwes_event *) 0 ;
    char *arg2 = (char *) 0 ;
    struct in_addr *arg3 = (struct in_addr *) 0 ;
    int result;
    zval **args[4];
    int argbase=0 ;
    
    if (this_ptr && this_ptr->type==IS_OBJECT) {
        /* fake this_ptr as first arg (till we can work out how to do it better */
        argbase++;
    }
    if(((ZEND_NUM_ARGS() + argbase )!= 3) || (zend_get_parameters_array_ex(3-argbase, args)!= SUCCESS)) {
        WRONG_PARAM_COUNT;
    }
    
    
    if(SWIG_ConvertPtr(*((0<argbase)?(&this_ptr):(args[0-argbase])), (void **) &arg1, SWIGTYPE_p_lwes_event) < 0) {
        zend_error(E_ERROR, "Type error in argument %d of lwes_event_get_IP_ADDR. Expected %s", 1-argbase, SWIGTYPE_p_lwes_event->name);
    }
    
    {
        if ((*args[1-argbase])->type == IS_NULL) {
            arg2 = NULL;
        } else {
            convert_to_string_ex(args[1-argbase]);
            arg2 = Z_STRVAL_PP(args[1-argbase]);
        }
        
    }
    
    if(SWIG_ConvertPtr(*args[2-argbase], (void **) &arg3, SWIGTYPE_p_in_addr) < 0) {
        zend_error(E_ERROR, "Type error in argument %d of lwes_event_get_IP_ADDR. Expected %s", 3-argbase, SWIGTYPE_p_in_addr->name);
    }
    
    result = (int)lwes_event_get_IP_ADDR(arg1,arg2,arg3);
    
    
    ZVAL_LONG(return_value,result);
    
}


ZEND_NAMED_FUNCTION(_wrap_lwes_event_set_BOOLEAN) {
    struct lwes_event *arg1 = (struct lwes_event *) 0 ;
    char *arg2 = (char *) 0 ;
    int arg3 ;
    int result;
    zval **args[4];
    int argbase=0 ;
    
    if (this_ptr && this_ptr->type==IS_OBJECT) {
        /* fake this_ptr as first arg (till we can work out how to do it better */
        argbase++;
    }
    if(((ZEND_NUM_ARGS() + argbase )!= 3) || (zend_get_parameters_array_ex(3-argbase, args)!= SUCCESS)) {
        WRONG_PARAM_COUNT;
    }
    
    
    if(SWIG_ConvertPtr(*((0<argbase)?(&this_ptr):(args[0-argbase])), (void **) &arg1, SWIGTYPE_p_lwes_event) < 0) {
        zend_error(E_ERROR, "Type error in argument %d of lwes_event_set_BOOLEAN. Expected %s", 1-argbase, SWIGTYPE_p_lwes_event->name);
    }
    
    {
        if ((*args[1-argbase])->type == IS_NULL) {
            arg2 = NULL;
        } else {
            convert_to_string_ex(args[1-argbase]);
            arg2 = Z_STRVAL_PP(args[1-argbase]);
        }
        
    }
    
    convert_to_long_ex(args[2-argbase]);
    arg3 = (int) Z_LVAL_PP(args[2-argbase]);
    
    result = (int)lwes_event_set_BOOLEAN(arg1,arg2,arg3);
    
    
    ZVAL_LONG(return_value,result);
    
}


ZEND_NAMED_FUNCTION(_wrap_lwes_event_get_BOOLEAN) {
    struct lwes_event *arg1 = (struct lwes_event *) 0 ;
    char *arg2 = (char *) 0 ;
    int *arg3 = (int *) 0 ;
    int result;
    int intr3 ;
    int force3 ;
    zval **args[4];
    int argbase=0 ;
    zval ** _saved[1] ;
    
    if (this_ptr && this_ptr->type==IS_OBJECT) {
        /* fake this_ptr as first arg (till we can work out how to do it better */
        argbase++;
    }
    if(((ZEND_NUM_ARGS() + argbase )!= 3) || (zend_get_parameters_array_ex(3-argbase, args)!= SUCCESS)) {
        WRONG_PARAM_COUNT;
    }
    
    
    if(SWIG_ConvertPtr(*((0<argbase)?(&this_ptr):(args[0-argbase])), (void **) &arg1, SWIGTYPE_p_lwes_event) < 0) {
        zend_error(E_ERROR, "Type error in argument %d of lwes_event_get_BOOLEAN. Expected %s", 1-argbase, SWIGTYPE_p_lwes_event->name);
    }
    
    {
        if ((*args[1-argbase])->type == IS_NULL) {
            arg2 = NULL;
        } else {
            convert_to_string_ex(args[1-argbase]);
            arg2 = Z_STRVAL_PP(args[1-argbase]);
        }
        
    }
    
    /* inout typemap for int using convert_to_long_ex and ZVAL_LONG */
    if(SWIG_ConvertPtr(*args[2-argbase], (void **) &arg3, SWIGTYPE_p_int) < 0) {
        /* So... we didn't get a ref or ptr, but can it be reasonably 
               co-erced into what we were looking for a ref of or ptr to? */
        if (!PZVAL_IS_REF(*args[2-argbase]) && (*args[2-argbase])->type==IS_NULL) {
            // null passed not by reference means pass NULL
            arg3 = NULL;
            force3=0;
        } else if (PZVAL_IS_REF(*args[2-argbase]) &&
        ((*args[2-argbase])->type==IS_STRING ||
        (*args[2-argbase])->type==IS_LONG ||
        /* Null passed by reference means we want a value back */
        (*args[2-argbase])->type==IS_NULL ||
        (*args[2-argbase])->type==IS_BOOL ||
        (*args[2-argbase])->type==IS_DOUBLE)) {
            convert_to_long_ex(args[2-argbase]);
            intr3 = (int) (*args[2-argbase])->value.lval;
            arg3 = &intr3;
            /* have to passback arg$arg too */
            force3=1;
        } else {
            /* wasn't a pre/ref/thing, OR anything like an int thing */
            force3=0;
            zend_error(E_ERROR, "Type error in argument %d of lwes_event_get_BOOLEAN. Expected %s or at least something looking vaguely like a number hopefully passed by reference", 3-argbase, SWIGTYPE_p_int->name);
        }
    } else force3=0;
    
    _saved[0] = args[2-argbase];
    result = (int)lwes_event_get_BOOLEAN(arg1,arg2,arg3);
    
    
    ZVAL_LONG(return_value,result);
    
    
    if (force3) {
        /* pass back arg3 through params (_saved[0]) if we can */
        if(! PZVAL_IS_REF(*_saved[0])) {
            zend_error(E_WARNING, "Parameter %d of lwes_event_get_BOOLEAN wasn't passed by reference [argout int *, int &]",3-argbase);
        } else {
            ZVAL_LONG(*_saved[0],intr3);	
        }
    }
    
}


ZEND_NAMED_FUNCTION(_wrap_lwes_event_destroy) {
    struct lwes_event *arg1 = (struct lwes_event *) 0 ;
    int result;
    zval **args[2];
    int argbase=0 ;
    
    if (this_ptr && this_ptr->type==IS_OBJECT) {
        /* fake this_ptr as first arg (till we can work out how to do it better */
        argbase++;
    }
    if(((ZEND_NUM_ARGS() + argbase )!= 1) || (zend_get_parameters_array_ex(1-argbase, args)!= SUCCESS)) {
        WRONG_PARAM_COUNT;
    }
    
    
    if(SWIG_ConvertPtr(*((0<argbase)?(&this_ptr):(args[0-argbase])), (void **) &arg1, SWIGTYPE_p_lwes_event) < 0) {
        zend_error(E_ERROR, "Type error in argument %d of lwes_event_destroy. Expected %s", 1-argbase, SWIGTYPE_p_lwes_event->name);
    }
    
    result = (int)lwes_event_destroy(arg1);
    
    
    ZVAL_LONG(return_value,result);
    
}


ZEND_NAMED_FUNCTION(_wrap_lwes_event_create_no_db) {
    char *arg1 = (char *) 0 ;
    struct lwes_event *result;
    zval **args[2];
    int argbase=0 ;
    
    if (this_ptr && this_ptr->type==IS_OBJECT) {
        /* fake this_ptr as first arg (till we can work out how to do it better */
        argbase++;
    }
    if(((ZEND_NUM_ARGS() + argbase )!= 1) || (zend_get_parameters_array_ex(1-argbase, args)!= SUCCESS)) {
        WRONG_PARAM_COUNT;
    }
    
    {
        if ((*((0<argbase)?(&this_ptr):(args[0-argbase])))->type == IS_NULL) {
            arg1 = NULL;
        } else {
            convert_to_string_ex(((0<argbase)?(&this_ptr):(args[0-argbase])));
            arg1 = Z_STRVAL_PP(((0<argbase)?(&this_ptr):(args[0-argbase])));
        }
        
    }
    result = (struct lwes_event *)lwes_event_create_no_db(arg1);
    
    
    SWIG_SetPointerZval(return_value, (void *)result, SWIGTYPE_p_lwes_event, 0);
    
}


/* NEW Destructor style */
static ZEND_RSRC_DTOR_FUNC(_wrap_destroy_p_lwes_event_type_db) {
/* bah! No destructor for this simple type!! */
}
/* NEW Destructor style */
static ZEND_RSRC_DTOR_FUNC(_wrap_destroy_p_in_addr) {
/* bah! No destructor for this simple type!! */
}
/* NEW Destructor style */
static ZEND_RSRC_DTOR_FUNC(_wrap_destroy_p_lwes_emitter) {
/* bah! No destructor for this simple type!! */
}
/* NEW Destructor style */
static ZEND_RSRC_DTOR_FUNC(_wrap_destroy_p_p_char) {
/* bah! No destructor for this simple type!! */
}
/* NEW Destructor style */
static ZEND_RSRC_DTOR_FUNC(_wrap_destroy_p_lwes_event) {
/* bah! No destructor for this simple type!! */
}
/* NEW Destructor style */
static ZEND_RSRC_DTOR_FUNC(_wrap_destroy_p_unsigned_int) {
/* bah! No destructor for this simple type!! */
}
/* NEW Destructor style */
static ZEND_RSRC_DTOR_FUNC(_wrap_destroy_p_unsigned_short) {
/* bah! No destructor for this simple type!! */
}
/* NEW Destructor style */
static ZEND_RSRC_DTOR_FUNC(_wrap_destroy_p_short) {
/* bah! No destructor for this simple type!! */
}
/* NEW Destructor style */
static ZEND_RSRC_DTOR_FUNC(_wrap_destroy_p_int) {
/* bah! No destructor for this simple type!! */
}




/* end wrapper section */
/* init section */
#ifdef __cplusplus
extern "C" {
#endif
ZEND_GET_MODULE(lwes)
#ifdef __cplusplus
}
#endif

PHP_MSHUTDOWN_FUNCTION(lwes)
{
    return SUCCESS;
}
PHP_MINIT_FUNCTION(lwes)
{
    int i;
    for (i = 0; swig_types_initial[i]; i++) {
        swig_types[i] = SWIG_TypeRegister(swig_types_initial[i]);
    }
/* oinit subsection */

/* Register resource destructors for pointer types */
le_swig__p_lwes_event_type_db=zend_register_list_destructors_ex(_wrap_destroy_p_lwes_event_type_db,NULL,(char *)(SWIGTYPE_p_lwes_event_type_db->name),module_number);
SWIG_TypeClientData(SWIGTYPE_p_lwes_event_type_db,&le_swig__p_lwes_event_type_db);
le_swig__p_in_addr=zend_register_list_destructors_ex(_wrap_destroy_p_in_addr,NULL,(char *)(SWIGTYPE_p_in_addr->name),module_number);
SWIG_TypeClientData(SWIGTYPE_p_in_addr,&le_swig__p_in_addr);
le_swig__p_lwes_emitter=zend_register_list_destructors_ex(_wrap_destroy_p_lwes_emitter,NULL,(char *)(SWIGTYPE_p_lwes_emitter->name),module_number);
SWIG_TypeClientData(SWIGTYPE_p_lwes_emitter,&le_swig__p_lwes_emitter);
le_swig__p_p_char=zend_register_list_destructors_ex(_wrap_destroy_p_p_char,NULL,(char *)(SWIGTYPE_p_p_char->name),module_number);
SWIG_TypeClientData(SWIGTYPE_p_p_char,&le_swig__p_p_char);
le_swig__p_lwes_event=zend_register_list_destructors_ex(_wrap_destroy_p_lwes_event,NULL,(char *)(SWIGTYPE_p_lwes_event->name),module_number);
SWIG_TypeClientData(SWIGTYPE_p_lwes_event,&le_swig__p_lwes_event);
le_swig__p_unsigned_int=zend_register_list_destructors_ex(_wrap_destroy_p_unsigned_int,NULL,(char *)(SWIGTYPE_p_unsigned_int->name),module_number);
SWIG_TypeClientData(SWIGTYPE_p_unsigned_int,&le_swig__p_unsigned_int);
le_swig__p_unsigned_short=zend_register_list_destructors_ex(_wrap_destroy_p_unsigned_short,NULL,(char *)(SWIGTYPE_p_unsigned_short->name),module_number);
SWIG_TypeClientData(SWIGTYPE_p_unsigned_short,&le_swig__p_unsigned_short);
le_swig__p_short=zend_register_list_destructors_ex(_wrap_destroy_p_short,NULL,(char *)(SWIGTYPE_p_short->name),module_number);
SWIG_TypeClientData(SWIGTYPE_p_short,&le_swig__p_short);
le_swig__p_int=zend_register_list_destructors_ex(_wrap_destroy_p_int,NULL,(char *)(SWIGTYPE_p_int->name),module_number);
SWIG_TypeClientData(SWIGTYPE_p_int,&le_swig__p_int);
CG(active_class_entry) = NULL;
/* end oinit subsection */

    return SUCCESS;
}
PHP_RINIT_FUNCTION(lwes)
{
/* cinit subsection */
/* end cinit subsection */

/* vinit subsection */
/* end vinit subsection */

    return SUCCESS;
}
PHP_RSHUTDOWN_FUNCTION(lwes)
{
    return SUCCESS;
}
PHP_MINFO_FUNCTION(lwes)
{

  php_info_print_table_start();
  php_info_print_table_header(2, "LWES support", "enabled");
  php_info_print_table_end();

}
/* end init section */
