<?php

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

global $LWES_LOADED__;
if ($LWES_LOADED__) return;
$LWES_LOADED__ = true;

/* if our extension has not been loaded, do what we can */
if (!extension_loaded("php_lwes")) {
	if (!dl("php_lwes.so")) return;
}



?>
