/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

/*
  +----------------------------------------------------------------------+
  | PHP version 4.0                                                      |
  +----------------------------------------------------------------------+
  | Copyright (c) 1997, 1998, 1999, 2000, 2001 The PHP Group             |
  +----------------------------------------------------------------------+
  | This source file is subject to version 2.02 of the PHP license,      |
  | that is bundled with this package in the file LICENSE, and is        |
  | available at through the world-wide-web at                           |
  | http://www.php.net/license/2_02.txt.                                 |
  | If you did not receive a copy of the PHP license and are unable to   |
  | obtain it through the world-wide-web, please send a note to          |
  | license@php.net so we can mail you a copy immediately.               |
  +----------------------------------------------------------------------+
  | Authors:                                                             |
  |                                                                      |
  +----------------------------------------------------------------------+
 */


#ifndef PHP_LWES_H
#define PHP_LWES_H

extern zend_module_entry lwes_module_entry;
#define phpext_lwes_ptr &lwes_module_entry

#ifdef PHP_WIN32
# define PHP_LWES_API __declspec(dllexport)
#else
# define PHP_LWES_API
#endif

PHP_MINIT_FUNCTION(lwes);
PHP_MSHUTDOWN_FUNCTION(lwes);
PHP_RINIT_FUNCTION(lwes);
PHP_RSHUTDOWN_FUNCTION(lwes);
PHP_MINFO_FUNCTION(lwes);

ZEND_NAMED_FUNCTION(_wrap_create_db);
ZEND_NAMED_FUNCTION(_wrap_destroy_db);
ZEND_NAMED_FUNCTION(_wrap_create_emitter);
ZEND_NAMED_FUNCTION(_wrap_create_emitter_with_ttl);
ZEND_NAMED_FUNCTION(_wrap_emit);
ZEND_NAMED_FUNCTION(_wrap_emitto);
ZEND_NAMED_FUNCTION(_wrap_destroy_emitter);
ZEND_NAMED_FUNCTION(_wrap_create_event);
ZEND_NAMED_FUNCTION(_wrap_create_event_with_encoding);
ZEND_NAMED_FUNCTION(_wrap_set_uint16);
ZEND_NAMED_FUNCTION(_wrap_get_uint16);
ZEND_NAMED_FUNCTION(_wrap_set_int16);
ZEND_NAMED_FUNCTION(_wrap_get_int16);
ZEND_NAMED_FUNCTION(_wrap_set_uint32);
ZEND_NAMED_FUNCTION(_wrap_get_uint32);
ZEND_NAMED_FUNCTION(_wrap_set_int32);
ZEND_NAMED_FUNCTION(_wrap_get_int32);
ZEND_NAMED_FUNCTION(_wrap_set_uint64);
ZEND_NAMED_FUNCTION(_wrap_get_uint64);
ZEND_NAMED_FUNCTION(_wrap_set_int64);
ZEND_NAMED_FUNCTION(_wrap_get_int64);
ZEND_NAMED_FUNCTION(_wrap_set_string);
ZEND_NAMED_FUNCTION(_wrap_get_string);
ZEND_NAMED_FUNCTION(_wrap_set_ip_addr);
ZEND_NAMED_FUNCTION(_wrap_get_ip_addr);
ZEND_NAMED_FUNCTION(_wrap_set_boolean);
ZEND_NAMED_FUNCTION(_wrap_get_boolean);
ZEND_NAMED_FUNCTION(_wrap_destroy_event);
ZEND_NAMED_FUNCTION(_wrap_current_time_millis);
/*If you declare any globals in php_lwes.h uncomment this:
ZEND_BEGIN_MODULE_GLOBALS(lwes)
ZEND_END_MODULE_GLOBALS(lwes)
*/
#ifdef ZTS
#define LWES_D  zend_lwes_globals *lwes_globals
#define LWES_DC  , LWES_D
#define LWES_C  lwes_globals
#define LWES_CC  , LWES_C
#define LWES_SG(v)  (lwes_globals->v)
#define LWES_FETCH()  zend_lwes_globals *lwes_globals = ts_resource(lwes_globals_id)
#else
#define LWES_D
#define LWES_DC
#define LWES_C
#define LWES_CC
#define LWES_SG(v)  (lwes_globals.v)
#define LWES_FETCH()
#endif

#endif /* PHP_LWES_H */
